using CryptoExchange.Net.Converters;
using Newtonsoft.Json;
using Switcheo.Net.Converters;
using System;

namespace Switcheo.Net.Objects
{
    /// <summary>
    /// Information received after a successful execution of a withdrawal
    /// </summary>
    public class SwitcheoWithdrawalExecutedResult
    {
        /// <summary>
        /// The type of event
        /// </summary>
        [JsonProperty("event_type")]
        public string EventType { get; set; }

        /// <summary>
        /// The withdrawn amount
        /// </summary>
        [JsonProperty("amount")]
        [JsonConverter(typeof(NeoAssetAmountConverter))]
        public decimal Amount { get; set; }

        /// <summary>
        /// The withdrawn asset
        /// </summary>
        [JsonProperty("asset_id")]
        [JsonConverter(typeof(SupportedAssetConverter))]
        public SupportedAsset Asset { get; set; }

        // TODO: Ask for an enumeration of what "status" can be
        /// <summary>
        /// The withdrawal status
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; }

        /// <summary>
        /// The withdrawal id generated by Switcheo
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// The blockchain that the withdrawal exists on
        /// </summary>
        [JsonProperty("blockchain")]
        [JsonConverter(typeof(BlockchainTypeConverter))]
        public BlockchainType Blockchain { get; set; }

        [JsonProperty("reason_code")]
        public int ReasonCode { get; set; }

        /// <summary>
        /// The withdrawal address
        /// </summary>
        [JsonProperty("address")]
        public string Address { get; set; }

        /// <summary>
        /// The withdrawal transaction hash
        /// </summary>
        [JsonProperty("transaction_hash")]
        public string TransactionHash { get; set; }

        /// <summary>
        /// Time when the withdrawal was created
        /// </summary>
        [JsonProperty("created_at")]
        [JsonConverter(typeof(UTCDateTimeConverter))]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Time when the withdrawal was updated
        /// </summary>
        [JsonProperty("updated_at")]
        [JsonConverter(typeof(UTCDateTimeConverter))]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// The contract where the withdrawal was from
        /// </summary>
        [JsonProperty("contract_hash")]
        public string ContractHash { get; set; }
    }
}
