using Newtonsoft.Json;
using Switcheo.Net.Converters;
using System;

namespace Switcheo.Net.Objects
{
    /// <summary>
    /// Information about a specific offer
    /// </summary>
    public class SwitcheoOffer
    {
        /// <summary>
        /// The offer id generated by Switcheo
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Symbol of the token that the offer maker is offering
        /// </summary>
        [JsonProperty("offer_asset")]
        [JsonConverter(typeof(SupportedAssetConverter))]
        public SupportedAsset OfferAsset { get; set; }

        /// <summary>
        /// Symbol of the token that the offer maker wants
        /// </summary>
        [JsonProperty("want_asset")]
        [JsonConverter(typeof(SupportedAssetConverter))]
        public SupportedAsset WantAsset { get; set; }

        /// <summary>
        /// Remaining amount of the OfferAsset that has not been taken by other orders
        /// </summary>
        [JsonProperty("available_amount")]
        [JsonConverter(typeof(NeoAssetAmountConverter))]
        public decimal AvailableAmount { get; set; }

        /// <summary>
        /// Total amount of the OfferAsset
        /// </summary>
        [JsonProperty("offer_amount")]
        [JsonConverter(typeof(NeoAssetAmountConverter))]
        public decimal OfferAmount { get; set; }

        /// <summary>
        /// Total amount of the WantAsset
        /// </summary>
        [JsonProperty("want_amount")]
        [JsonConverter(typeof(NeoAssetAmountConverter))]
        public decimal WantAmount { get; set; }

        public override string ToString()
        {
            return string.Format("{{ Id : {0}, OfferAsset : {1}, WantAsset : {2}, AvailableAmount : {3}, OfferAmount : {4}, WantAmount : {5} }}",
                this.Id, this.OfferAsset.ToString(), this.WantAsset.ToString(), this.AvailableAmount, this.OfferAsset, this.WantAmount);
        }
    }
}
