using Newtonsoft.Json;
using System;

namespace Switcheo.Net.Objects
{
    /// <summary>
    /// Information received after a successful creation of a withdrawal
    /// </summary>
    public class SwitcheoWithdrawalCreationResult
    {
        /// <summary>
        /// The withdrawal id generated by Switcheo
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }
    }
}
