using Newtonsoft.Json;
using Switcheo.Net.Converters;
using System;

namespace Switcheo.Net.Objects
{
    /// <summary>
    /// Information about a specific offer
    /// </summary>
    public class SwitcheoOffer
    {
        /// <summary>
        /// The offer id generated by Switcheo
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Symbol of the token that the offer maker is offering
        /// </summary>
        [JsonProperty("offer_asset")]
        [JsonConverter(typeof(TokenConverter))]
        public SwitcheoToken OfferAsset { get; set; }

        /// <summary>
        /// Symbol of the token that the offer maker wants
        /// </summary>
        [JsonProperty("want_asset")]
        [JsonConverter(typeof(TokenConverter))]
        public SwitcheoToken WantAsset { get; set; }

        [JsonProperty("available_amount")]
        private string _AvailableAmount { get; set; }

        /// <summary>
        /// Remaining amount of the OfferAsset that has not been taken by other orders
        /// </summary>
        [JsonIgnore]
        public decimal AvailableAmount
        {
            get
            {
                return SwitcheoHelpers.FromAssetAmount(this._AvailableAmount, this.OfferAsset?.Precision);
            }
            set
            {
                this._AvailableAmount = SwitcheoHelpers.ToAssetAmount(value);
            }
        }

        [JsonProperty("offer_amount")]
        private string _OfferAmount { get; set; }

        /// <summary>
        /// Total amount of the OfferAsset
        /// </summary>
        [JsonIgnore]
        public decimal OfferAmount
        {
            get
            {
                return SwitcheoHelpers.FromAssetAmount(this._OfferAmount, this.OfferAsset?.Precision);
            }
            set
            {
                this._OfferAmount = SwitcheoHelpers.ToAssetAmount(value);
            }
        }

        [JsonProperty("want_amount")]
        private string _WantAmount { get; set; }

        /// <summary>
        /// Total amount of the WantAsset
        /// </summary>
        [JsonIgnore]
        public decimal WantAmount
        {
            get
            {
                return SwitcheoHelpers.FromAssetAmount(this._WantAmount, this.WantAsset?.Precision);
            }
            set
            {
                this._WantAmount = SwitcheoHelpers.ToAssetAmount(value);
            }
        }

        public override string ToString()
        {
            return string.Format("{{ Id : {0}, OfferAsset : {1}, WantAsset : {2}, AvailableAmount : {3}, OfferAmount : {4}, WantAmount : {5} }}",
                this.Id, this.OfferAsset.ToString(), this.WantAsset.ToString(), this.AvailableAmount, this.OfferAsset, this.WantAmount);
        }
    }
}
