using CryptoExchange.Net.Converters;
using Newtonsoft.Json;
using Switcheo.Net.Converters;
using System;

namespace Switcheo.Net.Objects
{
    /// <summary>
    /// Information about a specific trade
    /// </summary>
    public class SwitcheoTrade
    {
        /// <summary>
        /// The trade id generated by Switcheo
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Amount of tokens that is given by the trade to the offer that it is filling
        /// </summary>
        [JsonProperty("fill_amount")]
        public string RawFillAmount { get; set; }

        /// <summary>
        /// Amount of tokens that the trade takes from the offer's AvailableAmount that it is filling.
        /// </summary>
        [JsonProperty("take_amount")]
        public string RawTakeAmount { get; set; }

        /// <summary>
        /// Date of the trade
        /// </summary>
        [JsonProperty("event_time")]
        [JsonConverter(typeof(UTCDateTimeConverter))]
        public DateTime EventTime { get; set; }

        /// <summary>
        /// Whether the side of the trade is a buy
        /// </summary>
        [JsonProperty("is_buy")]
        public bool IsBuy { get; set; }

        public override string ToString()
        {
            return string.Format("{{ Id : {0}, RawFillAmount : {1}, RawTakeAmount : {2}, EventTime : {3}, IsBuy : {4} }}", this.Id,
                this.RawFillAmount, this.RawTakeAmount, this.EventTime, this.IsBuy);
        }
    }
}
