using Newtonsoft.Json;
using System;

namespace Switcheo.Net.Objects
{
    /// <summary>
    /// Information received after a successful creation of a cancellation
    /// </summary>
    public class SwitcheoCancellationCreationResult
    {
        /// <summary>
        /// The cancellation id generated by Switcheo
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// The cancellation associated transaction 
        /// </summary>
        [JsonProperty("transaction")]
        public SwitcheoTransaction Transaction { get; set; }

        /// <summary>
        /// The script parameters
        /// </summary>
        [JsonProperty("script_params")]
        public SwitcheoScriptParams ScriptParams { get; set; }
    }
}
